### PR TITLE
Fixes: Python executable not found

### LINKED ISSUE #223: Improve error message when Python executable is not found.
Hey,

Upon executing `enderpy check test.py` command, an error occurred: `Error: × No such file or directory (os error 2)`.

This was confusing because `tokenize` and `parse` worked properly with the same file. After inspecting the code and trying to debug, it turns out that I had no Python executable installed 😅

Wouldn't it be helpful for CLI users to have more explicit error messages?

(disclaimer: I don't know how to Rust)
```rust
fn get_python_executable() -> Result<PathBuf, String> {
    match std::process::Command::new("python")
        .arg("-c")
        .arg("import sys; print(sys.executable)")
        .output()
    {
        Ok(output) => {
            let path = String::from_utf8(output.stdout)
                .map_err(|_| "Failed to parse Python executable path".to_string())?;
            Ok(PathBuf::from(path.trim()))
        }
        Err(_) => Err("Python is not installed or not found in the system PATH".to_string()),
    }
}
```

### PR DESCRIPTION
**Pull request by hrolfurgylfa**
This fixes #223 and puts the Python executable into the settings struct.

### CODE REVIEW

File: enderpy/src/main.rs [hunk 1]
```diff
@@ -40,13 +40,26 @@ fn symbols(path: &Path) -> Result<()> {
 }
 
 fn get_python_executable() -> Result<PathBuf> {
```
Comment (Glyphack) [inline enderpy/src/main.rs:42]: Can you add a test case that checks the output of this? It should only check the last few parts of the path since it runs on the runner as well we cannot check the full path. So just checking the last part of the path is `python`.

Comment (hrolfurgylfa) [reply enderpy/src/main.rs:42]: Yeah, although it is testing the environment more than the code at that point right? I don't see it being too flakey though, so that should be fine, as long as all the environments the tests are run in have a python executable.

Will throw that in later today.

**Review by Glyphack — APPROVED** [review]

**Review by Glyphack — APPROVED** [review]
